
# MQTT brocker
mqtt:
  image: eclipse-mosquitto
  container_name: mosquitto
  restart: always
  ports:
    - 1883:1883
    - 9001:9001
  volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/mosquitto.passwd:/etc/mosquitto/mosquitto.passwd
    - ./mosquitto/data:/mosquitto/data/
    # - /var/log/mosquitto.log:/mosquitto/log/mosquitto.log
    - ./mosquitto/log:/mosquitto/log/
