# Home automation docker setup
version: "3.3"
services:

  # MQTT brocker
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.passwd:/etc/mosquitto/mosquitto.passwd
      - ./mosquitto/data:/mosquitto/data/
      - ./mosquitto/log:/mosquitto/log/
  
  # Zigbee2MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.10.0
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      # CC251 TODO Pass by id
      #- /dev/ttyUSB_cc2531:/dev/ttyACM0
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    environment:
      - "TZ=Europe/Amsterdam"
    depends_on:
      - mqtt

  # App Daemon
  appdaemon:
    container_name: appdaemon
    environment:
      EXTRA_CMD: -D INFO
    image: appdaemon:4.0.1
    ports:
      # TODO use "127.0.0.1:5051:5051" for access only internaly
      - "5051:5051"
    restart: unless-stopped
    environment:
      - "TZ=Europe/Amsterdam"
    depends_on:
      - assistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appdaemon:/conf
 
  # Home assistant
  assistant:
    image: homeassistant/raspberrypi3-homeassistant:0.104.3
    container_name: "hass"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8123"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 6
    network_mode: host
    ports:
      - 8123:8123
      - 8943:8943
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mqtt
