homeassistant:
  name: "My Home"
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: Europe/Amsterdam
  
  packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http: !include conf/http.yaml
# Text to speech
tts:
  - platform: google_translate

# MQTT broker
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret MQTT_username
  password: !secret MQTT_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# group: !include_dir_merge_named groups
light: !include lights.yaml
# automation: !include_dir_merge_list automation 
script: !include_dir_merge_named scripts
python_script:
