homeassistant: !include conf/homeassistant.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
http: !include conf/http.yaml

# Integrations
mqtt: !include conf/mqtt.yaml
group: !include_dir_merge_named conf/groups
light: !include conf/lights.yaml
scene: !include conf/scenes.yaml
python_script:

# Text to speech
tts:
  - platform: google_translate

# Interface
lovelace:
  mode: yaml
