title: Vlinder wooning

# Anchors
master-bedroom-lights: &master-bedroom-lights
  entity: light.master_bedroom
  type: light

hobby-room-lights: &living-room-lights
  entity: light.living_room
  type: light


# Views configuration

views:
  - path: default_view 
    title: Main
    cards:
      - type: horizontal-stack
        title: First floor
        cards:
          - type: entity-button
            entity: light.master_bedroom
            name: Bedroom
          - type: entity-button
            entity: light.tradfri_led_e27_color_600_02_light
            name: Kate's
          - type: entity-button
            entity: light.tradfri_led_e27_color_600_01_light
            name: Alex's
      - type: horizontal-stack
        title: Ground floor
        cards:
          - type: entity-button
            entity: light.living_room
          - type: entity-button
            entity: switch.wallswitch_01_switch
            icon: mdi:lightbulb
            name: Hallway
      - type: horizontal-stack
        title: Scenes
        cards:
          - type: entity-button
            entity: scene.romantic
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.romantic
          - type: entity-button
            entity: scene.party
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.party
          - type: entity-button
            entity: input_boolean.vacation_mode
      - entity: weather.home
        type: weather-forecast
      - type: 'custom:sun-card'
  - path: master_bedroom
    icon: mdi:bed-king
    title: Master Bedroom
    cards:
      - *master-bedroom-lights
  - path: hobby
    icon: mdi:desktop-mac
    title: Hobby Room
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_temperature
            name: Temperature
            graph: line
            unit: '°C'
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_humidity
            name: Humidity
            graph: line
            unit: '%'
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_pressure
            name: Pressure
            graph: line
            unit: 'hPa'
  - path: livinf_room
    icon: mdi:sofa
    title: Living Room
    cards:
      - *living-room-lights
  - path: outdoor
    icon: mdi:tree
    title: Outdoor
    badges:
      - sun.sun
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:sun-card'
          - entity: switch.control_outlet_01
            name: Garden Lights
            type: button
          - entity: light.tradfri_let_e27_806_01
            name: Porch lights
            type: light
  - path: system_state
    icon: mdi:settings
    title: System Overview
    badges:
      - binary_sensor.updater
      - person.admin
      - sun.sun
    cards:
      - type: entities
        title: Zigbee2mqtt
        show_header_toggle: false
        entities:
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: sensor.zigbee2mqtt_version
          - entity: sensor.zigbee2mqtt_coordinator_version

resources:
  - url: /local/community/home-assistant-sun-card.js
    type: module 
