title: Vlinder wooning

# Anchors
master-bedroom-lights: &master-bedroom-lights
  entity: light.master_bedroom
  type: light

hobby-room-lights: &hobby-room-lights
  entity: light.hobby_room
  type: light

# Views configuration

views:
  - path: default_view 
    title: Main
    cards:
      - type: entities
        title: Lights
        entities:
          - light.master_bedroom
          - light.hobby_room
      - entity: weather.home
        type: weather-forecast
  - path: master_bedroom
    icon: mdi:bed-king
    cards:
      - *master-bedroom-lights
  - path: hobby
    icon: mdi:desktop-mac
    cards:
      - *hobby-room-lights
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_temperature
            name: Temperature
            graph: line
            unit: '°C'
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_humidity
            name: Humidity
            graph: line
            unit: '%'
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_pressure
            name: Pressure
            graph: line
            unit: 'hPa'
  - path: system_state
    icon: mdi:settings
    badges:
      - binary_sensor.updater
      - person.admin
      - sensor.tradfri_button_action
      - sensor.tradfri_button_battery
      - sensor.tradfri_button_linkquality
      - sensor.tradfri_led_linkquality
      - sun.sun
    cards:
      - type: entities
        title: Zigbee2mqtt
        show_header_toggle: false
        entities:
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: sensor.zigbee2mqtt_version
          - entity: sensor.zigbee2mqtt_coordinator_version
          - type: divider
          - entity: switch.zigbee2mqtt_main_join
          - entity: timer.zigbee_permit_join

