title: Vlinder wooning

# Anchors

hobby-room-lights: &living-room-lights
  entity: light.living_room
  type: light


# Views configuration

views:
  - path: default_view 
    title: Main
    cards:
      - type: vertical-stack
        title: Lights master
        cards:
        - type: glance
          title: First floor
          entities:
            - entity: light.master_bedroom
              name: Master
              tap_action:
                action: toggle
            - entity: light.tradfri_led_e27_color_600_01_light
              name: Alex's
              tap_action:
                action: toggle
            - entity: light.tradfri_led_e27_color_600_02_light
              name: Kate's
              tap_action:
                action: toggle
            - entity: light.living_room
              name: Living Room
              icon: mdi:lightbulb
              tap_action:
                action: toggle
        - type: glance
          title: Ground floor
          entities:
            - entity: light.tradfri_let_e27_806_01
              name: Porch lights
              tap_action:
                action: toggle
            - entity: switch.control_outlet_01
              name: Garden light
              icon: mdi:lightbulb
              tap_action:
                action: toggle
      #- type: horizontal-stack
      #  title: Scenes
      #  cards:
      #    - type: entity-button
      #      entity: scene.romantic
      #      tap_action:
      #        action: call-service
      #        service: scene.turn_on
      #        service_data:
      #          entity_id: scene.romantic
      #    - type: entity-button
      #      entity: scene.party
      #      tap_action:
      #        action: call-service
      #        service: scene.turn_on
      #        service_data:
      #          entity_id: scene.party
      #    - type: entity-button
      #      entity: input_boolean.vacation_mode
      - type: vertical-stack
        title: Outside
        cards:
          - type: sensor
            name: Reality
            entity: sensor.hue_occ_sensor_01_temperature
          - type: weather-forecast
            entity: weather.home
          - type: 'custom:sun-card'
  - path: master_bedroom
    icon: mdi:bed-king
    title: Master Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: light 
            entity: light.master_bedroom
            name: Bedroom
          - type: light
            entity: light.tradfri_led_e27_color_600_02_light
            name: Kate's
          - type: light
            entity: light.tradfri_led_e27_color_600_01_light
            name: Alex's
  - path: hobby
    icon: mdi:desktop-mac
    title: Hobby Room
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_temperature
            name: Temperature
            graph: line
            unit: '°C'
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_humidity
            name: Humidity
            graph: line
            unit: '%'
          - type: sensor
            entity: sensor.xiaomi_aqara_th_1_pressure
            name: Pressure
            graph: line
            unit: 'hPa'
  - path: livinf_room
    icon: mdi:sofa
    title: Living Room
    cards:
      - *living-room-lights
  - path: outdoor
    icon: mdi:tree
    title: Outdoor
    badges:
      - sun.sun
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:sun-card'
          - entity: switch.control_outlet_01
            name: Garden Lights
            type: button
          - entity: light.tradfri_let_e27_806_01
            name: Porch lights
            type: light
  - path: system_state
    icon: mdi:wrench
    title: System Overview
    badges:
      - binary_sensor.updater
      - person.admin
      - sun.sun
    cards:
      - type: entities
        title: Zigbee2mqtt
        show_header_toggle: false
        entities:
          - entity: sensor.zigbee2mqtt_bridge_state
          - entity: sensor.zigbee2mqtt_version
          - entity: sensor.zigbee2mqtt_coordinator_version
      - type: vertical-stack
        title: Batteries state
        cards:
          - type: entities
            entities:
              - type: custom:battery-entity
                entity: sensor.tradfri_button_01_battery
              - type: custom:battery-entity
                entity: sensor.tradfri_button_02_battery
              - type: custom:battery-entity
                entity: sensor.tradfri_button_03_battery
              - type: custom:battery-entity
                entity: sensor.tradfri_occ_sensor_01_battery
              - type: custom:battery-entity
                entity: sensor.xiaomi_aqara_th_1_battery
              - type: custom:battery-entity
                entity: sensor.hue_occ_sensor_01_battery
              - type: custom:battery-entity
                entity: sensor.hue_wall_switch_01_battery

resources:
  - url: /local/community/home-assistant-sun-card.js
    type: module 
  - url: /local/community/battery-entity.js?v=0.2
    type: module
