- alias: Tradfri short click
  trigger:
    platform: state
    entity_id: sensor.tradfri_button_action 
    to: 'toggle'
  action:
    service: python_script.earendil 
    data:
      entity_id: light.bedroom_lights
      operation: toggle

- alias: Tradfri bright up
  trigger:
    platform: state
    entity_id: sensor.tradfri_button_action
    to: brightness_up_click
  action:
    service: python_script.earendil
    data:
      entity_id: light.bedroom_lights
      operation: dim_up

- alias: Tradfri bright down
  trigger:
    platform: state
    entity_id: sensor.tradfri_button_action
    to: brightness_down_click
  action:
    service: python_script.earendil
    data:
      entity_id: light.bedroom_lights
      operation: dim_down
