tradfri:
  description: "Light controll script that support IKEA tradfri controll actions"
  fields:
    entity_id:
      description: Entity id
    operation:
      description: "Script operation, possible options [toggle, turn_on, dim_up, dim_down, dim_hold_up]"
      example: toggle
    level:
      description: Dim level step
      example: 5
    transition:
      description: Transition time, optional use 1 by default
      example: 1
    light_attribute:
      description: Long press change attribute, by default is brightness [brightness]
      example: brightness 
