- id: '1632942235784'
  alias: Switch On At Sunset
  description: Garden lights control
  use_blueprint:
    path: Knuspel/switches_on_at_sunset.yaml
    input:
      target_switch:
        entity_id: switch.control_outlet_01
      elevation_shift: -3

- alias: Outside Lights off at 12pm midnight
  trigger:
    platform: time
    at: "23:59:00"
  action:
    service: switch.turn_off
    entity_id: switch.control_outlet_01
