- alias: Garden Lights off at 12pm midnight
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: switch.turn_off
    entity_id: switch.control_outlet_01

- alias: Switch Garden lights on at Sunset
  description: Garden lights control
  use_blueprint:
    path: Knuspel/switches_on_at_sunset.yaml
    input:
      target_switch:
        entity_id: switch.control_outlet_01
      elevation_shift: -3

- alias: Porch lights
  description: ''
  use_blueprint:
    path: local/motion_sun_light.yaml
    input:
      motion_entity: binary_sensor.hue_occ_sensor_01_occupancy
      elevation_shift: -2
      target_light:
        entity_id: light.tradfri_let_e27_806_01
      target_brightness: 85
      until_time: 00:00:00

- alias: Porch light button control
  description: 'Control porch light with button'
  variables:
    entities:
      - light.tradfri_let_e27_806_01
  trigger:
    - entity_id: sensor.tradfri_button_03_action
      platform: state
      to: 'on'
    - entity_id: sensor.tradfri_button_03_action
      platform: state
      to: 'off'
  condition: []
  action:
    - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == ''on'' }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ entities }}"
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == ''off'' }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ entities }}"

