blueprint:
  name: Switch On At Sunset
  description: Turn on the following switches at sunset
  domain: automation
  input:
    target_switch:
      name: Switches
      description: This is the switch (or switches) that will be activated at sunset
      selector:
        target:
          entity:
            domain: switch
    elevation_shift:
      name: Elevation Shift
      description: Using an elevation offset (height of sun relative to the horizon)
        to shift the sunset trigger, either earlier or later. Positive values bring
        the automation start time forward, whilst negative values delay the start
        time.
      default: 0.0
      selector:
        number:
          min: -10.0
          max: 10.0
          mode: slider
          step: 1.0
  source_url: https://gist.github.com/Knuspel/2aff78a59bae9bec0633adbee0e866d4
mode: single
variables:
  target_switch: !input 'target_switch'
trigger:
  platform: numeric_state
  entity_id: sun.sun
  attribute: elevation
  below: !input 'elevation_shift'
condition:
  condition: sun
  after: sunrise
  after_offset: 01:00:00
action:
- service: switch.turn_on
  target: !input 'target_switch'
